# Generated by Django 3.1.1 on 2020-12-31 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(choices=[('AT', 'Artist'), ('CP', 'Composer'), ('AR', 'Arranger'), ('CD', 'Conductor'), ('EN', 'Ensemble')], max_length=2)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('added_by', models.CharField(default='admin', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('spotify_uri', models.CharField(blank=True, max_length=200, verbose_name='Spotify URI')),
                ('youtube_url', models.CharField(blank=True, max_length=200, verbose_name='YouTube URL')),
                ('other_url', models.CharField(blank=True, max_length=200, verbose_name='Other URL')),
                ('added_by', models.CharField(default='admin', max_length=150)),
                ('last_edit_by', models.CharField(default='admin', max_length=150)),
                ('notes', models.TextField(blank=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.album')),
                ('arranger', models.ManyToManyField(related_name='arranger_song_set', to='music.Entity')),
                ('artist', models.ManyToManyField(related_name='artist_song_set', to='music.Entity')),
                ('composer', models.ManyToManyField(related_name='composer_song_set', to='music.Entity')),
                ('conductor', models.ManyToManyField(related_name='conductor_song_set', to='music.Entity')),
                ('ensemble', models.ManyToManyField(related_name='ensemble_song_set', to='music.Entity')),
                ('playlists', models.ManyToManyField(to='music.Playlist')),
            ],
        ),
        migrations.CreateModel(
            name='EntityAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.ManyToManyField(to='music.Entity')),
            ],
        ),
    ]
