# Generated by Django 3.1.1 on 2020-12-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entityalias',
            old_name='person',
            new_name='entity',
        ),
        migrations.RemoveField(
            model_name='entity',
            name='role',
        ),
    ]
