# Generated by Django 3.1.1 on 2020-09-13 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='url_spotify_text',
            new_name='uri_spotify_text',
        ),
    ]
