# Generated by Django 3.1.1 on 2020-12-31 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20201231_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityalias',
            name='alias',
            field=models.CharField(default='test', max_length=150),
            preserve_default=False,
        ),
    ]
