# Generated by Django 3.1.1 on 2020-09-13 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20200913_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='conductor_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='song',
            name='orchestra_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='song',
            name='artist_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='composer_text',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='song',
            name='uri_spotify_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
