# Generated by Django 3.1.1 on 2020-09-14 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_auto_20200913_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='url_other_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='song',
            name='url_youtube_text',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
