# Generated by Django 3.1.1 on 2020-09-14 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20200914_1713'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='title_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist_text',
            new_name='artist',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='composer_text',
            new_name='composer',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='conductor_text',
            new_name='conductor',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='orchestra_text',
            new_name='orchestra',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='uri_spotify_text',
            new_name='spotify_uri',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='title_text',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='url_youtube_text',
            new_name='youtube_url',
        ),
        migrations.RemoveField(
            model_name='song',
            name='url_other_text',
        ),
        migrations.AddField(
            model_name='song',
            name='other_url',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
