# Generated by Django 3.1.1 on 2020-09-22 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20200917_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='other_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='Other URL'),
        ),
        migrations.AlterField(
            model_name='song',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=200, verbose_name='YouTube URL'),
        ),
    ]
