# Generated by Django 3.1.1 on 2021-01-02 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0007_auto_20201231_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='arranger',
            new_name='arrangers',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='artist',
            new_name='artists',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='composer',
            new_name='composers',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='conductor',
            new_name='conductors',
        ),
        migrations.RenameField(
            model_name='song',
            old_name='ensemble',
            new_name='ensembles',
        ),
    ]
