# Generated by Django 3.1.1 on 2021-01-03 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0008_auto_20210102_1522'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='soloists',
            field=models.ManyToManyField(blank=True, related_name='soloists_song_set', to='music.Entity'),
        ),
        migrations.AlterField(
            model_name='song',
            name='arrangers',
            field=models.ManyToManyField(blank=True, related_name='arrangers_song_set', to='music.Entity'),
        ),
        migrations.AlterField(
            model_name='song',
            name='artists',
            field=models.ManyToManyField(blank=True, related_name='artists_song_set', to='music.Entity'),
        ),
        migrations.AlterField(
            model_name='song',
            name='composers',
            field=models.ManyToManyField(blank=True, related_name='composers_song_set', to='music.Entity'),
        ),
        migrations.AlterField(
            model_name='song',
            name='conductors',
            field=models.ManyToManyField(blank=True, related_name='conductors_song_set', to='music.Entity'),
        ),
        migrations.AlterField(
            model_name='song',
            name='ensembles',
            field=models.ManyToManyField(blank=True, related_name='ensembles_song_set', to='music.Entity'),
        ),
    ]
