# Generated by Django 3.1.1 on 2021-01-03 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0009_auto_20210102_1918'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='soloists',
        ),
    ]
