# Generated by Django 3.1.1 on 2020-09-25 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0010_auto_20200924_1842'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='notes',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='description_text',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
