# Generated by Django 3.1.1 on 2020-09-25 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0011_auto_20200924_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='description_text',
            new_name='description',
        ),
    ]
