# Generated by Django 3.1.1 on 2020-09-25 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20200924_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='arranger',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
