# Generated by Django 3.1.1 on 2020-09-25 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_song_arranger'),
    ]

    operations = [
        migrations.RenameField(
            model_name='song',
            old_name='orchestra',
            new_name='ensemble',
        ),
    ]
