# Generated by Django 3.1.1 on 2020-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20200924_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='last_edit_by',
            field=models.CharField(blank='admin', max_length=150),
        ),
    ]
