# Generated by Django 3.1.1 on 2020-09-30 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0015_song_last_edit_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='album',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='song',
            name='last_edit_by',
            field=models.CharField(default='admin', max_length=150),
        ),
    ]
